CHANGE REPLICATION SOURCE TO
    SOURCE_HOST='mysql_master',
    SOURCE_PORT=3306,
    SOURCE_USER='repl',
    SOURCE_PASSWORD='slavepass',
    SOURCE_SSL=0,
    GET_SOURCE_PUBLIC_KEY=1;

START REPLICA;